environment:
  info_version: 2.3

version: 2.0.{build}

clone_folder: c:\utfUnknown
image: Visual Studio 2019
configuration: Release
platform: Any CPU
nuget:
  project_feed: true
init:
- git config --global core.autocrlf true
build_script:
- ps: dotnet build -c Release 
test_script:
- ps: cd .\tests\
- ps: dotnet test
- ps: cd ..
after_build:
- ps: msbuild -t:Pack .\src\ -p:Configuration=Release  -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -verbosity:minimal
- ps: Get-ChildItem '**\test-diag.log' | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
artifacts:
- path: '**\*.nupkg'
- path: '**\*.snupkg'
- path: '**\test-diag.log'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(info_version)
  package_version: $(info_version)
  assembly_version: 2.0.0.0
  file_version: '{version}'
  informational_version: $(info_version)
deploy:
- provider: NuGet
  api_key:
    secure: AJukx1Xao4KhoyfVO3Cblf3thOZQX8B1H6pH4af9e3+drfsYY2sClu4yEhIopbE8
  on:
    branch: master
